[project]
name = 'Forestry-FSC-Compliance-Network'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.chain-of-custody-timber-tracking]
path = 'contracts/chain-of-custody-timber-tracking.clar'
clarity_version = 3
epoch = '3.2'

[contracts.forest-concession-registry]
path = 'contracts/forest-concession-registry.clar'
clarity_version = 3
epoch = '3.2'

[contracts.fsc-label-verification]
path = 'contracts/fsc-label-verification.clar'
clarity_version = 3
epoch = '3.2'

[contracts.illegal-logging-incident-tracking]
path = 'contracts/illegal-logging-incident-tracking.clar'
clarity_version = 3
epoch = '3.2'

[contracts.reforestation-credit-incentives]
path = 'contracts/reforestation-credit-incentives.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
